accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import SignupView


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # CHANGE PASSWORD
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name = 'accounts/password_change_form.html',
        success_url = reverse_lazy('accounts:password_change_done')
    ),
         name = 'password_change'),

    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name = 'accounts/password_change_done.html'),
         name = 'password_change_done'
    ),

    # RESET PASSWORD
    path('reset/',
         auth_views.PasswordResetView.as_view(
            template_name = 'accounts/password_reset.html',
            email_template_name = 'accounts/password_reset_email.html',
            subject_template_name = 'accounts/password_reset_subject.txt',
            success_url = reverse_lazy('accounts:password_reset_done')
         ),
         name = 'password_reset'),
    path('reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_done.html'),
         name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name = 'accounts/password_reset_confirm.html',
            success_url = reverse_lazy('accounts:password_reset_complete')
         ),
         name = 'password_reset_confirm'),
    path('reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name = 'password_reset_complete'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.topics, name='topics'),
    path('<int:pk>/new/', views.new_topic, name='new'),
    path('<int:pk>/titluri/<int:topic_pk>/', views.postari, name='discutii'),
    path('<int:pk>/titluri/<int:topic_pk>/new', views.new_post, name='comment'),
]

retetedelicioase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.utils.html import mark_safe
from markdown import markdown
from django.contrib.auth.models import User


class Categorii(models.Model):
    name = models.CharField(max_length=150, blank=False)
    description = models.CharField(max_length=200, blank=False)

    class Meta:
        verbose_name = 'Categorie'
        verbose_name_plural = 'Categorii'

    def count_posts(self):
        return Discutii.objects.filter(topic__categorie=self).count()

    def last_post(self):
        return Discutii.objects.filter(topic__categorie=self).order_by('-created_at').first()

    def __str__(self):
        return self.name


class Topics(models.Model):
    subject = models.CharField(max_length=100, unique=True, blank=False)
    last_updated = models.DateTimeField(auto_now=True)
    categorie = models.ForeignKey(Categorii, related_name='topics', on_delete=models.CASCADE)
    reteta = models.TextField(max_length=5000, blank=False, default='Text reteta')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics', null=True, blank=True)

    class Meta:
        verbose_name = 'Titlu'
        verbose_name_plural = 'Titluri'

    def get_reteta_as_markdown(self):
        return mark_safe(markdown(self.reteta, safe_mode='escape'))

    def __str__(self):
        return self.subject


class Discutii(models.Model):
    message = models.TextField(max_length=4000, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(Topics, related_name='posts', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'Discutie'
        verbose_name_plural = 'Discutii'

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    def __str__(self):
        return self.message

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput,
                                help_text='Introduceti minim 8 caractere',
                                label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput,
                                help_text='Introduceti aceeasi parola ca mai sus',
                                label='Confirm Password')
    username = forms.CharField(help_text='Userul ales sa aiba minim 4 caractere', widget=forms.TextInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

core/forms.py
from django import forms
from .models import Topics, Discutii

class NewTopicForm(forms.ModelForm):
    reteta = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Topics
        fields = ['subject', 'reteta',]


class NewCommentForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Discutii
        fields = ['message',]

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .forms import SignupForm

# Create your views here.
def signup(request):
    return render(request, 'accounts/signup.html')

class SignupView(generic.CreateView):
    template_name = 'accounts/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('accounts:login')

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Categorii, Topics
from .forms import NewTopicForm, NewCommentForm
from django.contrib.auth.decorators import login_required

def index(request):
    categorii = Categorii.objects.all()
    return render(request, 'core/index.html', {'categorii': categorii})

@login_required
def topics(request, pk):
    # categorie = Categorii.objects.get(pk=pk)
    categorie = get_object_or_404(Categorii, pk=pk)

    return render(request, 'core/topics.html', {'categorie': categorie})

@login_required
def postari(request, pk, topic_pk):
    # topic = Topics.objects.get(categorie__pk=pk, pk=topic_pk)
    topic = get_object_or_404(Topics, categorie__pk=pk, pk=topic_pk)
    return render(request, 'core/discutii.html', {'topic': topic})


@login_required
def new_topic(request, pk):
    # categorie = Categorii.objects.get(pk=pk)
    categorie = get_object_or_404(Categorii, pk=pk)

    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.categorie = categorie
            topic.save()
            return redirect('core:topics', pk=categorie.pk)
    else:
        form = NewTopicForm()
    return render(request, 'core/reteta noua.html', {'categorie':categorie, 'form':form})


@login_required
def new_post(request, pk, topic_pk):
    topic = get_object_or_404(Topics, categorie__pk=pk, pk=topic_pk)

    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.topic = topic
            message.save()
            return redirect('core:discutii', pk=pk, topic_pk=topic_pk)
    else:
        form = NewCommentForm()
    return render(request, 'core/comentariu nou.html', {'topic':topic, 'form':form})

accounts/templates/accounts/base_acc.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Retete Delicioase - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

        <style rel='stylesheet'>
            #titlu{
                font-size: 2em;
                font-family: 'Permanent Marker', cursive;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <ul class="nav navbar-nav navbar-logo mx-auto">
                <li class="nav-item"><a id='titlu' class="navbar-brand" href="{% url 'core:index' %}">Retete Delicioase</a></li>
            </ul>
        </nav>
        <div class="container">
            <br>
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card border-primary mb-3">
                        <div class="card-header "><h3 class="text-center">{% block card_title %} {% endblock %}</h3></div>
                        <div class="card-body ">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base_acc.html' %}
{% load bootstrap3 %}

{% block card_title %}

{% endblock %}

{% block content %}

    <form method="POST" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <input type="submit" class="btn btn-primary btn-block" value="Signup">
        {% endbuttons %}
        <p class="text-center">Allready have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
        <p class="text-center"><a href="{% url 'accounts:password_reset' %}">Reset password</a></p>
    </form>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'accounts/base_acc.html' %}

{% block title %}
    Password Change Done
{% endblock %}

{% block card_title %}
    Password Change
{% endblock %}

{% block content %}
    <h2>Password changed with success!</h2>
    <h4 class="text-center"><a href="{% url 'core:index' %}" class="btn btn-success btn-block">Go to Home Page</a></h4>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'accounts/base_acc.html' %}
{% load bootstrap3 %}


{% block title %}
    Password Change
{% endblock %}

{% block card_title %}
    Change Password
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% bootstrap_form form show_help=False %}
        <input type="submit" class="btn btn-warning btn-block" value="Change Password">

    </form>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base_acc.html' %}
{% load bootstrap3 %}

{% block title %}
    Password Reset
{% endblock %}

{% block card_title %}
    Reset Password
{% endblock %}

{% block content %}
    {% if form.errors %}
        <p>Incorrect email address</p>
    {% endif %}
    <h5>Forgot password? Enter email address below!</h5>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

            <input type="submit" class="btn btn-danger btn-block" value="Reset"><br>
            <p class="text-center"><a href="{% url 'accounts:login' %}">Log In</a></p>

    </form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base_acc.html' %}

{% block title %}
    Password Reset
{% endblock %}

{% block card_title %}
    Password Reset
{% endblock %}

{% block content %}
<p>
    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.
</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_acc.html' %}
{% load bootstrap3 %}

{% block title %}
    Password Reset Confirmation
{% endblock %}

{% block card_title %}
    Password Reset Confirmation
{% endblock %}

{% block content %}
{% if validlink %}
    <h3>Enter new password!</h3>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form show_help=False%}
        {% buttons %}
            <input type="submit" class="btn btn-success btn-block" value="Change Password">
        {% endbuttons %}
    </form>
{% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
{% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base_acc.html' %}

{% block title %}
    Password Reset
{% endblock %}

{% block card_title %}
    Password Reset
{% endblock %}

{% block content %}
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered.
        You should receive them shortly.
    </p>
    <p>
        If you don't receive an email, please make sure you've entered the address you registered with,
        and check your spam folder.
    </p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}


If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Retete Delicioase Team
{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base_acc.html' %}
{% load bootstrap3 %}

{% block card_title %}

{% endblock %}

{% block content %}

    <form method="POST" novalidate>
        {% csrf_token %}
        {% bootstrap_form form show_help=False %}
        {% buttons %}
            <input type="submit" class="btn btn-primary btn-block" value="Signup">
        {% endbuttons %}
        <p class="text-center">Allready have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
    </form>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Retete Delicioase</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
        <style rel='stylesheet'>
            #titlu{
                font-size: 2em;
                font-family: 'Permanent Marker', cursive;
            }
        </style>

        {% block stylesheet %}{% endblock %}

    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:index' %}" id="titlu">Retete Delicioase</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_superuser %}
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                </ul>
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle btn btn-outline-secondary" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ user.username.title }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                              <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                            </div>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link"
                               style="font-family: 'Permanent Marker', cursive; font-size: 1.5em"
                               href="{% url 'accounts:login' %}">
                                Log In</a></li>
                        <li class="nav-item">
                            <a class="nav-link ml-2"
                               style="font-family: 'Permanent Marker', cursive; font-size: 1.5em"
                               href="{% url 'accounts:signup' %}">
                                Sign Up</a></li>


                    {% endif %}
                </ul>
            </div>
        </div>
        </nav>

        <div class="container">
            <p></p>
            {% block breadcrumb %}
            {% endblock %}
        </div>

        <div class="container justify-content-center">
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        {% block javascript %}{% endblock %}

    </body>
</html>

core/templates/core/comentariu nou.html
{% extends 'core/base.html' %}

{% load bootstrap3 %}

{% block javascript %}
    <script>
        var simplemde = new SimpleMDE();
    </script>
{% endblock %}

{% block breadcrumb %}

    <div class="container">
        <h4>
            <a href="{% url 'core:index' %}">Categorii</a>/
            <a href="{% url 'core:topics' topic.categorie.pk %}">{{ topic.categorie.name }}</a>/
            <a href="{% url 'core:discutii' topic.categorie.pk topic.pk %}">{{ topic.subject }}</a>/
            Adauga comentariu
        </h4>
    </div>

{% endblock %}

{% block content %}

        <form method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
    {#        {% bootstrap_form form %}#}
            <button class="btn btn-primary" type="submit">Post</button>

        </form>


    <p></p>
    {% for msg in topic.posts.all %}
        {% if msg.message %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-2">
                        <p>USER</p>
                    </div>

                    <div class="col-lg-7">
                        {{ msg.get_message_as_markdown|safe|linebreaksbr }}
                    </div>

                    <div class="col-lg-2 ml-auto">
                        <p><small><strong>Created:</strong>{{ msg.created_at }}</small><br>
                            <small><strong>Updated:</strong>{{ msg.updated_at }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <p></p>
    {% endfor %}

{% endblock %}

core/templates/core/discutii.html
{% extends 'core/base.html' %}

{% load bootstrap3 %}

{% block breadcrumb %}
    <div class="container">
        <h4>
            <a href="{% url 'core:index' %}">Categorii</a>/
            <a href="{% url 'core:topics' topic.categorie.pk %}">{{ topic.categorie.name }}</a>/
            {{ topic.subject }}
        </h4>
    </div>
{% endblock %}

{% block content %}

    <div class="container">
        <a class="btn btn-primary" href="{% url 'core:comment' topic.categorie.pk topic.pk %}">Comentariu nou</a>
        <p></p>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-9">
                    {{ topic.get_reteta_as_markdown|safe|linebreaks }}
                </div>
                <div class="col-lg-2 ml-auto">
                    <strong><i>Created:{{ topic.last_updated }}</i></strong>
                </div>
            </div>
        </div>
    </div>


    {% for msg in topic.posts.all %}
        {% if msg.message %}
        <p></p>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-2">
                        <p>{{ msg.created_by.username.title }}</p>
                    </div>

                    <div class="col-lg-7">
                        {{ msg.get_message_as_markdown|safe|linebreaksbr }}
                    </div>

                    <div class="col-lg-2 ml-auto">
                        <p><small><strong>Created:</strong>{{ msg.created_at }}</small><br>
                            <small><strong>Updated:</strong>{{ msg.updated_at }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

    {% endfor %}


{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}


{% block breadcrumb %}
    <div class="container">
        <h4>Categorii</h4>
    </div>
{% endblock %}

{% block content %}

    <table class="table">
        <thead>
            <tr>
                <th>Retete</th>
                <th style="text-align: center">Titluri</th>
                <th style="text-align: center">Postari</th>
                <th style="text-align: center">Ultima Postare</th>
            </tr>
        </thead>
        <tbody>
            {% for categ in categorii %}
                <tr>
                    <td>
                        <a href="{% url 'core:topics' categ.pk %}">{{ categ.name }}</a><br>
                        <small class="text-muted">{{ categ.description }}</small>
                    </td>
                    <td style="text-align: center">{{ categ.topics.count }}</td>
                    <td style="text-align: center">{{ categ.count_posts }}</td>
                    <td style="text-align: center">
                        {% with postare=categ.last_post %}
                            {% if postare %}
                                <a href="{% url 'core:discutii' categ.pk postare.topic.pk %}">{{ postare.created_at }}</a>
                            {% else %}
                                <small class="text-muted"><i>Nici o postare</i></small>
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

core/templates/core/reteta noua.html
{% extends 'core/base.html' %}

{% block javascript %}
    <script>
        var simplemde = new SimpleMDE();
    </script>
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <h4>
            <a href="{% url 'core:index' %}">Categorii</a>/
            <a href="{% url 'core:topics' categorie.pk %}">{{ categorie.name }}</a>/
            Reteta noua
        </h4>
        <p></p>
    </div>
{% endblock %}

{% block content %}

    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Post</button>
    </form>



{% endblock %}

core/templates/core/topics.html
{% extends 'core/base.html' %}

{% block breadcrumb %}
    <div class="container">
        <h4>
            <a href="{% url 'core:index' %}">Categorii</a>/{{ categorie.name }}
        </h4>
    </div>
{% endblock %}


{% block content %}

    <div class="container">
        <a class="btn btn-primary" href="{% url 'core:new' categorie.pk %}">Reteta Noua</a>
        <p></p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <td>Subiect</td>
                <td style="text-align: center">Postari</td>
                <td style="text-align: center">Utilizator</td>
                <td style="text-align: center">Ultimul post</td>

            </tr>
        </thead>
        <tbody>
            {% for topic in categorie.topics.all %}
                <tr>
                    <td><a href="{% url 'core:discutii' categorie.pk topic.pk %}">{{ topic.subject }}</a> </td>
                    <td style="text-align: center">{{ topic.posts.count }}</td>
                    <td style="text-align: center">{{ topic.starter.username.title }}</td>

                    <td style="text-align: center">{{ topic.last_updated }}</td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}